version: "2"
services:
  postgres:
    container_name: postgres-database
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  django:
    container_name: django
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start.sh
    image: django-server
    stdin_open: true
    tty: true
    volumes:
      - django-data:/var/www/data
    ports:
      - "8000:8000"

volumes:
  postgres-data:
  django-data:
